development:
  adapter: postgresql
  database: tweet_development
  pool: 5
  username: javi 
  password:
  timeout: 5000

test:
  adapter: postgresql
  database: tweet_test
  pool: 5
  username: javi 
  password:
  timeout: 5000

production:
  adapter: postgresql
  database: tweet_production
  pool: 5
  username: javi 
  password:
  timeout: 5000
