# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca2b501348aa3f2cd6e6f000e21781973c44dbcb4a2a7e774467be90438f7e8930f6a2f7c579d53b24955910c91a7f8bf45f001c8c918a3deb34c839f12bd36a

test:
  secret_key_base: dc43396e95d8d9ccdbf2c64c4321156fd4d196297fcc75bcf8f1338a59aba4eeda15e0f8b2cab1ac220b22fcdbeff93d3581798678271a985b17ca3ef9c9cd10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
